export  const productsObj =[
    {src:"/images/catalog-page/Marble Machine.jpg",
     image1: '/images/product-imgs/marble1.jpg',
     image2: '/images/product-imgs/marble2.jpg',
     image3: '/images/product-imgs/marble3.jpg',
     image4: '/images/product-imgs/marble4.jpg',
     filter: ["PLA+",'Blue','Game',5],
     title: 'Marble Machine',
     description: 'Spin The Cap For Hours Of Fun',
     price: 30,
     previousPrice:40,
     rating:"🌟🌟🌟🌟🌟",
     stock: 5,
     sku: 'PB35-0',
    },
    {src:"/images/catalog-page/Impossible Table.jpg",
     image1: '/images/product-imgs/Impossible Table1.jpg',
     image2: '/images/product-imgs/Impossible Table2.jpg',
     image3: '/images/product-imgs/Impossible Table3.jpg',
     image4: '/images/product-imgs/Impossible Table4.jpg',
     filter: ["PLA+",'White','Engineering',5],
     title: 'Impossible Table',
     description: 'What Kind Of Sorcery Is This? ',
     price: 15,
     previousPrice:22,
     rating:"🌟🌟🌟🌟🌟",
     stock: 2,
     sku: 'PLW06-0',
    },
    {src:"/images/catalog-page/Little Boat.jpg",
     image1: '/images/product-imgs/Little Boat1.jpg',
     image2: '/images/product-imgs/Little Boat2.jpg',
     image3: '/images/product-imgs/Little Boat3.jpg',
     image4: '/images/product-imgs/Little Boat4.jpg',
     filter: ["PLA",'Black','Toy',4],
     title: 'Little Boat',
     description: "Popeye The Sailor's Boat",
     price: 10,
     previousPrice:13,
     rating:"🌟🌟🌟🌟",
     stock: 4,
     sku: 'PB02-0'
    },
    {src:"/images/catalog-page/Jet Fighter.jpg",
     image1: '/images/product-imgs/Jet Fighter1.jpg',
     image2: '/images/product-imgs/Jet Fighter2.jpg',
     image3: '/images/product-imgs/Jet Fighter3.jpg',
     image4: '/images/product-imgs/Jet Fighter4.jpg',
     filter: ["PLA",'Black','Toy',4],
     title: 'Jet Fighter',
     description: 'Is That A Transformer? ',
     price: 15,
     previousPrice:21,
     rating:"🌟🌟🌟🌟",
     stock: 6,
     sku: 'PB06-0'
    },
    {src:"/images/catalog-page/Color Lithophane - Aoraki.jpg",
     image1: '/images/product-imgs/Color Lithophane - Aoraki1.jpg',
     image2: '/images/product-imgs/Color Lithophane - Aoraki2.jpg',
     image3: '/images/product-imgs/Color Lithophane - Aoraki3.jpg',
     image4: '/images/product-imgs/Color Lithophane - Aoraki4.jpg',
     filter: ["PLA+",'White','Lithophane',5],
     title: 'Color Lithophane - Aoraki',
     description: 'lithophane Your Moments',
     price: 25,
     previousPrice:30,
     rating:"🌟🌟🌟🌟🌟",
     stock: 1,
     sku: 'PLW05-0'
   },
   {src:"/images/catalog-page/Batmobile.jpg",
    image1: '/images/product-imgs/Batmobile1.jpg',
    image2: '/images/product-imgs/Batmobile2.jpg',
    image3: '/images/product-imgs/Batmobile3.jpg',
    image4: '/images/product-imgs/Batmobile4.jpg',
    filter: ["PLA+",'Blue','Toy',3],
    title: 'Batmobile',
    description: 'The Iconic 1989 Batmobile',
    price: 5,
    previousPrice:12,
    rating:"🌟🌟🌟",
    stock: 11,
    sku: 'PLB09-0'
  },
  {src:"/images/catalog-page/Bistable Mechanism.jpg",
    image1: '/images/product-imgs/Bistable Mechanism1.jpg',
    image2: '/images/product-imgs/Bistable Mechanism2.jpg',
    image3: '/images/product-imgs/Bistable Mechanism3.jpg',
    image4: '/images/product-imgs/Bistable Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',5],
    title: 'Bistable Mechanism',
    description: 'You Can Go Up, Or You Can Go Down',
    price: 25,
    previousPrice:28,
    rating:"🌟🌟🌟🌟🌟",
    stock: 1,
    sku: 'PLB07-1'
  },
  {src:"/images/catalog-page/Elephant Compliant Mechanism.jpg",
    image1: '/images/product-imgs/Elephant Compliant Mechanism1.jpg',
    image2: '/images/product-imgs/Elephant Compliant Mechanism2.jpg',
    image3: '/images/product-imgs/Elephant Compliant Mechanism3.jpg',
    image4: '/images/product-imgs/Elephant Compliant Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',4],
    title: 'Elephant Compliant Mechanism',
    description: 'Move His Tail To Witness The Magic',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟",
    stock: 1,
    sku: 'PLB07-2'
  },
  {src:"/images/catalog-page/mini crossbow.jpg",
    image1: '/images/product-imgs/mini crossbow1.jpg',
    image2: '/images/product-imgs/mini crossbow2.jpg',
    image3: '/images/product-imgs/mini crossbow3.jpg',
    image4: '/images/product-imgs/mini crossbow4.jpg',
    filter: ["PLA+",'White','Toy',5],
    title: 'Mini Crossbow',
    description: 'I Just Look Innocent, I Will Fight Back',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟🌟",
    stock: 15,
    sku: 'PLW12-0'
  },
  {src:"/images/catalog-page/Oriceps.jpg",
    image1: '/images/product-imgs/Oriceps1.jpg',
    image2: '/images/product-imgs/Oriceps2.jpg',
    image3: '/images/product-imgs/Oriceps3.jpg',
    image4: '/images/product-imgs/Oriceps4.jpg',
    filter: ["PLA+",'Blue','Engineering',1],
    title: 'Oriceps',
    description: 'Action Origami',
    price: 15,
    previousPrice:20,
    rating:"🌟",
    stock: 3,
    sku: 'PLB02-0'
  },
  {src:"/images/catalog-page/Tiny Jet Fighter.jpg",
    image1: '/images/product-imgs/Tiny Jet Fighter1.jpg',
    image2: '/images/product-imgs/Tiny Jet Fighter2.jpg',
    image3: '/images/product-imgs/Tiny Jet Fighter3.jpg',
    image4: '/images/product-imgs/Tiny Jet Fighter4.jpg',
    filter: ["PLA",'Black','Toy',2],
    title: 'Tiny Jet Fighter',
    description: 'Put Me In a Surprise Egg',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟",
    stock: 3,
    sku: 'PB04-0'
  },

];

//'What is a lithophane? To put it simply, its a 3D print of a photo which uses the thickness of the print to show varying shades of grey when illuminated from behind'