export  const productsObj =[
    {src:"/images/catalog-page/Marble Machine.jpg",
     image1: '/images/product-imgs/Marble Machine1.jpg',
     image2: '/images/product-imgs/Marble Machine2.jpg',
     image3: '/images/product-imgs/Marble Machine3.jpg',
     image4: '/images/product-imgs/Marble Machine4.jpg',
     filter: ["PLA+",'Blue','Game',5],
     title: 'Marble Machine',
     description: 'Spin The Cap For Hours Of Fun',
     price: 30,
     previousPrice:40,
     rating:"🌟🌟🌟🌟🌟",
     stock: 5,
     printingTime: 35,
     sku: 'PB35-0',
     related: ['Mini Crossbow'],
     size: 'Medium',
     note: 'Does not come with marbles',
    },
    {src:"/images/catalog-page/Impossible Table.jpg",
     image1: '/images/product-imgs/Impossible Table1.jpg',
     image2: '/images/product-imgs/Impossible Table2.jpg',
     image3: '/images/product-imgs/Impossible Table3.jpg',
     image4: '/images/product-imgs/Impossible Table4.jpg',
     filter: ["PLA+",'White','Engineering',5],
     title: 'Impossible Table',
     description: 'What Kind Of Sorcery Is This? ',
     price: 15,
     previousPrice:22,
     rating:"🌟🌟🌟🌟🌟",
     stock: 2,
     printingTime: 6,
     sku: 'PLW06-0',
     related: ['Bistable Mechanism','Elephant Compliant Mechanism','Oriceps'],
     size: 'Small',
     note: "Assembly is DIY",
    },
    {src:"/images/catalog-page/Little Boat.jpg",
     image1: '/images/product-imgs/Little Boat1.jpg',
     image2: '/images/product-imgs/Little Boat2.jpg',
     image3: '/images/product-imgs/Little Boat3.jpg',
     image4: '/images/product-imgs/Little Boat4.jpg',
     filter: ["PLA",'Black','Toy',4],
     title: 'Little Boat',
     description: "Popeye The Sailor's Boat",
     price: 10,
     previousPrice:13,
     rating:"🌟🌟🌟🌟",
     stock: 4,
     printingTime: 2,
     sku: 'PB02-0',
     related: ['Batmobile','Jet Fighter','Tiny Jet Fighter'],
     size: 'Small',
     note:"Does not float",
    },
    {src:"/images/catalog-page/Jet Fighter.jpg",
     image1: '/images/product-imgs/Jet Fighter1.jpg',
     image2: '/images/product-imgs/Jet Fighter2.jpg',
     image3: '/images/product-imgs/Jet Fighter3.jpg',
     image4: '/images/product-imgs/Jet Fighter4.jpg',
     filter: ["PLA",'Black','Toy',4],
     title: 'Jet Fighter',
     description: 'Is That A Transformer? ',
     price: 15,
     previousPrice:21,
     rating:"🌟🌟🌟🌟",
     stock: 6,
     printingTime: 6,
     sku: 'PB06-0',
     related: ['Batmobile','Little Boat','Tiny Jet Fighter'],
     size: 'Small',
     note: "",
    },
    {src:"/images/catalog-page/Color Lithophane - Aoraki.jpg",
     image1: '/images/product-imgs/Color Lithophane - Aoraki1.jpg',
     image2: '/images/product-imgs/Color Lithophane - Aoraki2.jpg',
     image3: '/images/product-imgs/Color Lithophane - Aoraki3.jpg',
     image4: '/images/product-imgs/Color Lithophane - Aoraki4.jpg',
     filter: ["PLA+",'White','Lithophane',5],
     title: 'Color Lithophane - Aoraki',
     description: 'lithophane Your Moments',
     price: 25,
     previousPrice:30,
     rating:"🌟🌟🌟🌟🌟",
     stock: 1,
     printingTime: 5,
     sku: 'PLW05-0',
     related: [],
     size: 'Various',
     note:"Come with various sizes",
   },
   {src:"/images/catalog-page/Batmobile.jpg",
    image1: '/images/product-imgs/Batmobile1.jpg',
    image2: '/images/product-imgs/Batmobile2.jpg',
    image3: '/images/product-imgs/Batmobile3.jpg',
    image4: '/images/product-imgs/Batmobile4.jpg',
    filter: ["PLA+",'Blue','Toy',3],
    title: 'Batmobile',
    description: 'The Iconic 1989 Batmobile',
    price: 5,
    previousPrice:12,
    rating:"🌟🌟🌟",
    stock: 11,
    printingTime: 9,
    sku: 'PLB09-0',
    related: ['Jet Fighter','Little Boat','Tiny Jet Fighter'],
    size: 'Medium',
    note:"Does not roll",
  },
  {src:"/images/catalog-page/Bistable Mechanism.jpg",
    image1: '/images/product-imgs/Bistable Mechanism1.jpg',
    image2: '/images/product-imgs/Bistable Mechanism2.jpg',
    image3: '/images/product-imgs/Bistable Mechanism3.jpg',
    image4: '/images/product-imgs/Bistable Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',5],
    title: 'Bistable Mechanism',
    description: 'You Can Go Up, Or You Can Go Down',
    price: 25,
    previousPrice:28,
    rating:"🌟🌟🌟🌟🌟",
    stock: 1,
    printingTime: 7,
    sku: 'PLB07-1',
    related: ['Impossible Table','Elephant Compliant Mechanism','Oriceps'],
    size:'Medium',
    note:"Bistable mechanisms are mechanical systems with two stable positions like a switch",
  },
  {src:"/images/catalog-page/Elephant Compliant Mechanism.jpg",
    image1: '/images/product-imgs/Elephant Compliant Mechanism1.jpg',
    image2: '/images/product-imgs/Elephant Compliant Mechanism2.jpg',
    image3: '/images/product-imgs/Elephant Compliant Mechanism3.jpg',
    image4: '/images/product-imgs/Elephant Compliant Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',4],
    title: 'Elephant Compliant Mechanism',
    description: 'Move His Tail To Witness The Magic',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟",
    stock: 1,
    printingTime: 2,
    sku: 'PLB07-2',
    related: ['Impossible Table','Bistable Mechanism','Oriceps'],
    size:'Medium',
    note:"Observe the trunk while moving his tail",
  },
  {src:"/images/catalog-page/Mini Crossbow.jpg",
    image1: '/images/product-imgs/Mini Crossbow1.jpg',
    image2: '/images/product-imgs/Mini Crossbow2.jpg',
    image3: '/images/product-imgs/Mini Crossbow3.jpg',
    image4: '/images/product-imgs/Mini Crossbow4.jpg',
    filter: ["PLA+",'White','Game',5],
    title: 'Mini Crossbow',
    description: 'I Just Look Innocent, I Will Fight Back',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟🌟",
    stock: 15,
    printingTime: 12,
    sku: 'PLW12-0',
    related: ['Marble Machine'],
    size:'Medium',
    note:"Load with Toothpick",
  },
  {src:"/images/catalog-page/Oriceps.jpg",
    image1: '/images/product-imgs/Oriceps1.jpg',
    image2: '/images/product-imgs/Oriceps2.jpg',
    image3: '/images/product-imgs/Oriceps3.jpg',
    image4: '/images/product-imgs/Oriceps4.jpg',
    filter: ["PLA+",'Blue','Engineering',1],
    title: 'Oriceps',
    description: 'Action Origami',
    price: 15,
    previousPrice:20,
    rating:"🌟",
    stock: 3,
    printingTime: 2,
    sku: 'PLB02-0',
    related: ['Impossible Table','Bistable Mechanism','Elephant Compliant Mechanism'],
    size:'Small',
    note:"",
  },
  {src:"/images/catalog-page/Tiny Jet Fighter.jpg",
    image1: '/images/product-imgs/Tiny Jet Fighter1.jpg',
    image2: '/images/product-imgs/Tiny Jet Fighter2.jpg',
    image3: '/images/product-imgs/Tiny Jet Fighter3.jpg',
    image4: '/images/product-imgs/Tiny Jet Fighter4.jpg',
    filter: ["PLA",'Black','Toy',2],
    title: 'Tiny Jet Fighter',
    description: 'Put Me In a Surprise Egg',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟",
    stock: 3,
    printingTime: 4,
    sku: 'PB04-0',
    related: ['Jet Fighter','Little Boat','Batmobile'],
    size:'Extra small',
    note:"",
  },

];

//'What is a lithophane? To put it simply, its a 3D print of a photo which uses the thickness of the print to show varying shades of grey when illuminated from behind'