export  const productsObj =[
    {src:"/images/catalog-page/Marble Machine.jpg",
     thumbnail: "/images/thumbnail/Marble Machine.jpg" ,
     image1: '/images/product-imgs/Marble Machine1.jpg',
     image2: '/images/product-imgs/Marble Machine2.jpg',
     image3: '/images/product-imgs/Marble Machine3.jpg',
     image4: '/images/product-imgs/Marble Machine4.jpg',
     filter: ["PLA+",'Blue','Game',5,'Featured'],
     title: 'Marble Machine',
     description: 'Spin The Cap For Hours Of Fun',
     productDescription: 'The tracks are fully 3d printed – It uses a worm style elevator to lift ball bearings up the tracks. This marble run is an impressive design that is 3D printed in a single part. Require  9.5mm (3/8inch) steel ball bearings for playing.',
     price: 30,
     previousPrice:40,
     rating:"🌟🌟🌟🌟🌟",
     special: 'Featured',
     stock: 5,
     printingTime: 35,
     sku: 'PB35-0',
     related: ['Mini Crossbow'],
     size: 'Medium',
     note: 'Does not come with marbles',
    },
    {src:"/images/catalog-page/Impossible Table.jpg",
     thumbnail: "/images/thumbnail/Impossible Table.jpg" ,
     image1: '/images/product-imgs/Impossible Table1.jpg',
     image2: '/images/product-imgs/Impossible Table2.jpg',
     image3: '/images/product-imgs/Impossible Table3.jpg',
     image4: '/images/product-imgs/Impossible Table4.jpg',
     filter: ["PLA+",'White','Engineering',5,'Featured'],
     title: 'Impossible Table',
     description: 'What Kind Of Sorcery Is This? ',
     productDescription: 'This is a hanging table top where tension forces are used to keep the table upright and balanced instead of compression forces on standard legs. The end result is an object that seems to defy gravity and physics.',
     price: 15,
     previousPrice:22,
     rating:"🌟🌟🌟🌟🌟",
     special: 'Featured',
     stock: 2,
     printingTime: 6,
     sku: 'PLW06-0',
     related: ['Bistable Mechanism','Elephant Compliant Mechanism','Oriceps'],
     size: 'Small',
     note: "Assembly is DIY",
    },
    {src:"/images/catalog-page/Little Boat.jpg",
     thumbnail: "/images/thumbnail/Little Boat.jpg" ,
     image1: '/images/product-imgs/Little Boat1.jpg',
     image2: '/images/product-imgs/Little Boat2.jpg',
     image3: '/images/product-imgs/Little Boat3.jpg',
     image4: '/images/product-imgs/Little Boat4.jpg',
     filter: ["PLA",'Black','Toy',4,'Featured'],
     title: 'Little Boat',
     description: "Popeye The Sailor's Boat",
     productDescription: 'The Little Boat is often used to test and benchmark 3D printers when they are reviewed, as the model includes a number of difficult-to-print features including: symmetry, overhanging curved surfaces, smooth surfaces, planar horizontal faces, large, small and slanted holes, low-slope-surfaces, first layer details and tiny surface details.',
     price: 10,
     previousPrice:13,
     rating:"🌟🌟🌟🌟",
     special: 'Featured',
     stock: 4,
     printingTime: 2,
     sku: 'PB02-0',
     related: ['Batmobile','Jet Fighter','Tiny Jet Fighter'],
     size: 'Small',
     note:"Does not float",
    },
    {src:"/images/catalog-page/Jet Fighter.jpg",
     thumbnail: "/images/thumbnail/Jet Fighter.jpg" ,
     image1: '/images/product-imgs/Jet Fighter1.jpg',
     image2: '/images/product-imgs/Jet Fighter2.jpg',
     image3: '/images/product-imgs/Jet Fighter3.jpg',
     image4: '/images/product-imgs/Jet Fighter4.jpg',
     filter: ["PLA",'Black','Toy',4,'Featured'],
     title: 'Jet Fighter',
     description: 'Is That A Transformer? ',
     productDescription: 'The Jet Fighter have variable-sweep wings, colloquially known as a "swing wing", is an airplane wing, or set of wings, that may be swept back and then returned to its original straight position during flight. ',
     price: 15,
     previousPrice:21,
     rating:"🌟🌟🌟🌟",
     special: 'Featured',
     stock: 6,
     printingTime: 6,
     sku: 'PB06-0',
     related: ['Batmobile','Little Boat','Tiny Jet Fighter'],
     size: 'Small',
     note: "",
    },
    {src:"/images/catalog-page/Color Lithophane - Aoraki.jpg",
     thumbnail: "/images/thumbnail/Color Lithophane - Aoraki.jpg" ,
     image1: '/images/product-imgs/Color Lithophane - Aoraki1.jpg',
     image2: '/images/product-imgs/Color Lithophane - Aoraki2.jpg',
     image3: '/images/product-imgs/Color Lithophane - Aoraki3.jpg',
     image4: '/images/product-imgs/Color Lithophane - Aoraki4.jpg',
     filter: ["PLA+",'White','Lithophane',5,'New'],
     title: 'Color Lithophane',
     description: 'lithophane Your Moments',
     productDescription: `A lithophane presents a three-dimensional image – completely different from two-dimensional engravings and daguerreotypes that are "flat". The images change characteristics depending on the light source behind them. The varying lightsource is what makes lithophanes more interesting to the viewer than two-dimensional pictures. In addition, With a colored image behind the Lithophane, you can recapture the moment.`,
     price: 25,
     previousPrice:30,
     rating:"🌟🌟🌟🌟🌟",
     special: 'New',
     stock: 1,
     printingTime: 5,
     sku: 'PLW05-0',
     related: [],
     size: 'Various',
     note:"Come with various sizes",
   },
   {src:"/images/catalog-page/Batmobile.jpg",
    thumbnail: "/images/thumbnail/Batmobile.jpg" ,
    image1: '/images/product-imgs/Batmobile1.jpg',
    image2: '/images/product-imgs/Batmobile2.jpg',
    image3: '/images/product-imgs/Batmobile3.jpg',
    image4: '/images/product-imgs/Batmobile4.jpg',
    filter: ["PLA+",'Blue','Toy',3,'New'],
    title: 'Batmobile',
    description: 'The Iconic 1989 Batmobile',
   productDescription: `Tim Burton's live-action films Batman (1989) presented a different version of the Batmobile. The Batmobile is both a heavily armored tactical assault vehicle and a personalized custom-built pursuit and capture vehicle that is used by Batman in his fight against crime`,
    price: 5,
    previousPrice:12,
    rating:"🌟🌟🌟",
    special: 'New',
    stock: 11,
    printingTime: 9,
    sku: 'PLB09-0',
    related: ['Jet Fighter','Little Boat','Tiny Jet Fighter'],
    size: 'Medium',
    note:"Does not roll",
  },
  {src:"/images/catalog-page/Bistable Mechanism.jpg",
    thumbnail: "/images/thumbnail/Bistable Mechanism.jpg" ,
    image1: '/images/product-imgs/Bistable Mechanism1.jpg',
    image2: '/images/product-imgs/Bistable Mechanism2.jpg',
    image3: '/images/product-imgs/Bistable Mechanism3.jpg',
    image4: '/images/product-imgs/Bistable Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',5,'New'],
    title: 'Bistable Mechanism',
    description: 'You Can Go Up, Or You Can Go Down',
    productDescription: `Bistable Mechanisms are mechanical systems with two stable positions. A switch is a very common bistable system. 
    These systems have two stable positions. These two positions correspond to a function of the mechanism (on/off) making these system very usefull in our everyday life even if they are extremely simples in terms of configurations.`,
    price: 25,
    previousPrice:28,
    rating:"🌟🌟🌟🌟🌟",
    special: 'New',
    stock: 1,
    printingTime: 7,
    sku: 'PLB07-1',
    related: ['Impossible Table','Elephant Compliant Mechanism','Oriceps'],
    size:'Medium',
    note:"Bistable mechanisms are mechanical systems with two stable positions like a switch",
  },
  {src:"/images/catalog-page/Elephant Compliant Mechanism.jpg",
    thumbnail: "/images/thumbnail/Elephant Compliant Mechanism.jpg" ,
    image1: '/images/product-imgs/Elephant Compliant Mechanism1.jpg',
    image2: '/images/product-imgs/Elephant Compliant Mechanism2.jpg',
    image3: '/images/product-imgs/Elephant Compliant Mechanism3.jpg',
    image4: '/images/product-imgs/Elephant Compliant Mechanism4.jpg',
    filter: ["PLA+",'Blue','Engineering',4,'New'],
    title: 'Compliant Mechanism',
    description: 'Move His Tail To Witness The Magic',
    productDescription: `This mechanism is a compliant mechanism that has motion similar to a double parallel mechanism. The mechanisms are examples of how compliant mechanisms can be used to create specific desired motions. The hole in the Elephant's trunk is a coupler point that rotates but does not translate, as if the point were pinned to ground but it is actually unconstrained.`,
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟",
    special: 'New',
    stock: 1,
    printingTime: 2,
    sku: 'PLB07-2',
    related: ['Impossible Table','Bistable Mechanism','Oriceps'],
    size:'Medium',
    note:"Observe the trunk while moving his tail",
  },
  {src:"/images/catalog-page/Mini Crossbow.jpg",
    thumbnail: "/images/thumbnail/Mini Crossbow.jpg" ,
    image1: '/images/product-imgs/Mini Crossbow1.jpg',
    image2: '/images/product-imgs/Mini Crossbow2.jpg',
    image3: '/images/product-imgs/Mini Crossbow3.jpg',
    image4: '/images/product-imgs/Mini Crossbow4.jpg',
    filter: ["PLA+",'White','Game',5,'Sale'],
    title: 'Mini Crossbow',
    description: 'I Just Look Innocent, I Will Fight Back',
    productDescription: 'This Mini-Crossbow pistol is perfect for target practice and small-game hunting. Use a fishing line as an arch and load the crossbow with toothpick.',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟🌟🌟🌟",
    special: 'Sale',
    stock: 15,
    printingTime: 12,
    sku: 'PLW12-0',
    related: ['Marble Machine'],
    size:'Medium',
    note:"Load with Toothpick",
  },
  {src:"/images/catalog-page/Oriceps.jpg",
    thumbnail: "/images/thumbnail/Oriceps.jpg" ,
    image1: '/images/product-imgs/Oriceps1.jpg',
    image2: '/images/product-imgs/Oriceps2.jpg',
    image3: '/images/product-imgs/Oriceps3.jpg',
    image4: '/images/product-imgs/Oriceps4.jpg',
    filter: ["PLA+",'Blue','Engineering',1,'Sale'],
    title: 'Oriceps',
    description: 'Action Origami',
    productDescription: `This Oriceps design is an example of a compliant mechanismthat  was made for application as a pair of forceps that were later adapted and implemented for use on one of Intuitive Surgical's da Vinci robots. This gripping mechanism could be used for applications in remote-controlled space tools, other surgical devices, household items, and toys.`,
    price: 15,
    previousPrice:20,
    rating:"🌟",
    special: 'Sale',
    stock: 3,
    printingTime: 2,
    sku: 'PLB02-0',
    related: ['Impossible Table','Bistable Mechanism','Elephant Compliant Mechanism'],
    size:'Small',
    note:"",
  },
  {src:"/images/catalog-page/Tiny Jet Fighter.jpg",
    thumbnail: "/images/thumbnail/Tiny Jet Fighter.jpg" ,
    image1: '/images/product-imgs/Tiny Jet Fighter1.jpg',
    image2: '/images/product-imgs/Tiny Jet Fighter2.jpg',
    image3: '/images/product-imgs/Tiny Jet Fighter3.jpg',
    image4: '/images/product-imgs/Tiny Jet Fighter4.jpg',
    filter: ["PLA",'Black','Toy',2,'Sale'],
    title: 'Tiny Jet Fighter',
    description: 'Put Me In a Surprise Egg',
    productDescription: 'A smaller version of the Jet Fighter. With variable-sweep wings that may be swept back and then returned to its original straight position during flight',
    price: 15,
    previousPrice:20,
    rating:"🌟🌟",
    special: 'Sale',
    stock: 3,
    printingTime: 4,
    sku: 'PB04-0',
    related: ['Jet Fighter','Little Boat','Batmobile'],
    size:'Extra small',
    note:"",
  },

];

//'What is a lithophane? To put it simply, its a 3D print of a photo which uses the thickness of the print to show varying shades of grey when illuminated from behind'